version: '2'

services:
    server:
        build:
            context: ../
            dockerfile: ./server/Dockerfile
        container_name: stock
        volumes: 
            - ../src:/etc/stock_work/src
            - ../notebooks:/etc/stock_work/notebooks
            - ../data:/etc/stock_work/data
        ports: 
            - "8888:8888"
            - "8000:8000"
            - "443:443"
            - "80:80"
        expose: 
            - "8888"